### ISSUE TITLE
Show better examples & names

### ISSUE THREAD

**Issue by canadaduane** [cblgh/paperslip#3]
Nice work! Remarkable how simple the code is that harnesses the hyperswarm network on the back end.

Currently the example usage shows "35c3" as the name of a share, and doesn't really go into detail on how to actually share something. I think you could show off quite a nice workflow:

----

In one terminal:
```
paperslip testshare
```

In another terminal:
```
echo "hello from another terminal" | paperslip testshare --stdin
```

**Comment by cblgh** [comment]
@canadaduane thank you! and wonderful suggestion, i updated the readme accordingly, thanks!
